title: RepoSense Report Test Title
repos:
  - repo: https://github.com/user/repo.git
    groups:
      - group-name: code
        globs:
          - "**.java"
      - group-name: tests
        globs:
          - "src/test**"
      - group-name: docs
        globs:
          - "docs**"
          - "**.adoc"
          - "**.md"
    branches:
      - branch: main
        blurb:
        ignore-glob-list:
          - "docs**"
        ignore-authors-list:
          - author1
          - author2
