title: RepoSense Report Test Title
repos:
  - repo: https://github.com/user/repo.git
    blurb: "My project"
    groups:
      - group-name: code
        globs:
          - "**.java"
      - group-name: tests
        globs:
          - "src/test**"
      - group-name: docs
        globs:
          - "docs**"
          - "**.adoc"
          - "**.md"
    branches:
      - branch: main
        authors:
          - author-git-host-id: johnDoe
            author-display-name: John Doe
            author-git-author-name: my home PC
            author-emails:
              - john@john.com
              - johny@mail.com
              - j@domain.com
        ignore-glob-list:
          - "docs**"
        ignore-authors-list:
          - author1
          - author2
