name: GitHub Actions build preview

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      -   completed

jobs:
  deploy:
    name: deploy to github action
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Download deployment artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: integration.yml
        run_id: ${{ github.event.workflow_run.id }}
        name: reposense-deployment
        path: .

    - name: Check existence of files
      run: ls -al

    - name: Deploy GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reposense-report
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: Rebuild pages at

    - name: Test connection to deployed website
      run: wget -S https://${{github.repository_owner}}.github.io/${{github.repository}}/pull/${{github.event.number}}